# Generated by Django 3.2 on 2021-04-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
